kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - kms:
        apiVersion: v2
        name: barbican
        endpoint: unix:///var/lib/kms/kms.sock
    - identity: {}
